# GitLab Workflow for building and deploying a Hugo site to GitHub Pages
# needs $MRX_DOCKER_USR - the account username for docker hub
# needs $MRX_DOCKER_PWD - the account password for docker hub
# needs $MRX_DOCKER_NS - the account namespace for docker hub e.g. metarexmedia
variables:
  IMAGE: www-metarex-media
  vGOLANG: "1.22"
  vHUGO: "0.133.0"
  BASE_URL: ""
  vDART: " 1.70.0"
  # node version `node` will install the latest version with nvm
  vNODE: node
  vDOCKER_IMAGE: "26.0"
  REGISTRY: hub.docker.com
  GIT_DEPTH: 0
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive
  TZ: Europe/London
  barkId: "GitLab:"
  # docker will fail to login unless the certdir is specified
  DOCKER_TLS_CERTDIR: "/certs"

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "rc"

stages:
  - test
  - build
  - deploy
  # - hook

default:
  image: golang:latest

# --- bark --------------------------------------------------------------------
bark:
  stage: build
  script:
    - curl https://mrmxf.com/get/clog | bash
    - clog Check
    - clog Check gitlab-env

# --- hugo --------------------------------------------------------------------
hugo:
  stage: build
  needs: [bark]
  script:
    # Install brotli
    - apt-get update
    - apt-get install -y brotli
    # install nvm for easy Node management
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
    # pull in the nvm env variables
    - source ~/.bashrc
    # Install Node.js
    - nvm install $vNODE
    # Install Dart Sass
    - curl -LJO https://github.com/sass/dart-sass/releases/download/${vDART}/dart-sass-${vDART}-linux-x64.tar.gz
    - tar -xf dart-sass-${vDART}-linux-x64.tar.gz
    - cp -r dart-sass/ /usr/local/bin
    - rm -rf dart-sass*
    - export PATH=/usr/local/bin/dart-sass:$PATH
    # Install Hugo
    - curl -LJO https://github.com/gohugoio/hugo/releases/download/v${vHUGO}/hugo_extended_${vHUGO}_linux-amd64.deb
    - apt-get install -y ./hugo_extended_${vHUGO}_linux-amd64.deb
    - rm hugo_extended_${vHUGO}_linux-amd64.deb
    # Install Node.js dependencies
    - |
      if [[ -f package-lock.json || -f npm-shrinkwrap.json ]] ; then
        npm ci  || true
      else
        npm i || true
      fi
    # Hugo fails unexpectedly if the theme folder does not exist.
    - mkdir -p themes/fohuw
    # Build
    - |
      hugo mod get
      hugo --gc --minify
    # Compress
    - find public -type f -regex '.*\.\(css\|html\|js\|txt\|xml\)$' -exec gzip -f -k {} \;
    - find public -type f -regex '.*\.\(css\|html\|js\|txt\|xml\)$' -exec brotli -f -k {} \;
    # Get website version
    - |
      vCODE=$(cat data/history.yaml | grep version | head -1 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
      echo "pushing website version $vCODE"
      echo "export vCODE=$vCODE"              >> job-chain.sh
      echo "export BRANCH=$CI_COMMIT_BRANCH"  >> job-chain.sh
  artifacts:
    paths:
      - public
      - job-chain.sh

# --- deploy ------------------------------------------------------------------
deploy:
  stage: deploy
  image: docker:$vDOCKER_IMAGE
  services:
    - docker:$vDOCKER_IMAGE-dind
  before_script:
    - echo "$MRX_DOCKER_PWD" | docker login -u "$MRX_DOCKER_USR" --password-stdin
    - docker info
  script:
    #create env from upstream dependencies
    - source job-chain.sh
    - echo "Deploying website version ($vCODE) from branch ($BRANCH)"

    - echo "Logged into docker($MRX_DOCKER_USR) via gitlab($GITLAB_USER_LOGIN)"
    #- docker buildx create --name multibuild
    #- docker buildx use multibuild

    - TARGETamd="$MRX_DOCKER_NS/$IMAGE-amd:$vCODE"
    - TARGETarm="$MRX_DOCKER_NS/$IMAGE-arm:$vCODE"

    #- docker buildx build -t $TARGET --push --platform linux/amd64,linux/arm64,linux/arm/v7 .
    - echo "Build & push to $TARGETamd"
    - docker buildx build -t "$TARGETamd" --push --platform linux/amd64 .
    - docker buildx imagetools inspect "$TARGETamd"

    - echo "Build & push to $TARGETarm"
    - docker buildx build -t "$TARGETarm" --push --platform linux/arm64 .
    - docker buildx imagetools inspect "$TARGETarm"

# --- hook ------------------------------------------------------------------
hook:
  stage: deploy
  needs: [deploy]
  script:
    - echo "fire the CI/CD hook to the wesbite signalling no errors"
    - curl https://staging.metarex.media/a/hook/cicd/gitlab/$IMAGE
