---
# Copyright ©2017-2025  Mr MXF   info@mrmxf.com
# BSD-3-Clause License           https://opensource.org/license/bsd-3-clause/
#   ___   ___         _             _   _      _            _              _                 _             _    
#  | _ \ | _ \  ___  | |__   _  _  (_) | |  __| |  ___   __| |  ___   __  | |__  ___   _ _  | |_    _  _  | |__ 
#  |  _/ |   / |___| | '_ \ | || | | | | | / _` | |___| / _` | / _ \ / _| | / / / -_) | '_| | ' \  | || | | '_ \
#  |_|   |_|_\       |_.__/  \_,_| |_| |_| \__,_|       \__,_| \___/ \__| |_\_\ \___| |_|   |_||_|  \_,_| |_.__/
#
#  GitHub Workflow to build & deploy the metarex website
#
# see job.build for secrets & vars

name: pr-build-dockerhub
run-name: "www-mrmxf-com pr 🥷${{ github.actor }}: 🏃‍➡️ ${{ github.workflow }} @ ${{ github.event.repository.name }}:${{ github.ref_name }}"

on:
  workflow_dispatch:            # run manually from Actions tab
  pull_request_target:
    types: [opened, reopened, synchronize, edited, review_requested, ready_for_review, review_request_removed]

# Ensure only one workflow runs at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

jobs:

  # Build job
  build:
    uses: mrmxf/clog/.github/workflows/build-hugo.yaml@main
    with:
      # artifact-name: kodata
      docker_ns: ${{ vars.DOCKER_NS }}
      bc-from: "trigger: event(${{ github.event_name }}) ref(${{ github.ref_name }})"
      bc-toast: "metarex.media PR 😺🎬(${{ github.workflow }}) 🥷${{ github.actor }} ⇒⇒ ${{ github.repository }}"
      bc-trigger: "${{ github.event.repository.html_url }}"

    secrets:
      docker_pat: ${{ secrets.DOCKER_PAT }}
      get_clog: ${{ secrets.GET_CLOG }}
      # provide a slack_webhook to get a slack message otherwise silence
      webhook_slack: ${{ secrets.HOOK_SLACK_LOGS }}
     
  dump-context:
    uses: mrmxf/clog/.github/workflows/dump-context.yaml@main
