---
# Copyright ©2017-2025  Mr MXF   info@mrmxf.com
# BSD-3-Clause License           https://opensource.org/license/bsd-3-clause/
#   _                         _             _   _      _            _              _                 _             _    
#  | |_   __ _   __ _   ___  | |__   _  _  (_) | |  __| |  ___   __| |  ___   __  | |__  ___   _ _  | |_    _  _  | |__ 
#  |  _| / _` | / _` | |___| | '_ \ | || | | | | | / _` | |___| / _` | / _ \ / _| | / / / -_) | '_| | ' \  | || | | '_ \
#   \__| \__,_| \__, |       |_.__/  \_,_| |_| |_| \__,_|       \__,_| \___/ \__| |_\_\ \___| |_|   |_||_|  \_,_| |_.__/
#               |___/                                                                                                   
#  GitHub Workflow to build & deploy the metarex website
#
# see job.build for secrets & vars

name: tag-build-dockerhub
run-name: "🥷${{ github.actor }}: 🏃‍➡️ ${{ github.workflow }} @ ${{ github.event.repository.name }}:${{ github.ref_name }}"

on:
  workflow_dispatch:            # run manually from Actions tab
  create:                       # run when a tag is created


# Default to bash
defaults:
  run:
    shell: bash

# Allow only one concurrent deployment, skipping runs queued between the run
# in-progress and latest queued. Allow cancelling in-progress runs.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:

  # Build job
  build:
    uses: mrmxf/clog/.github/workflows/build-hugo.yaml@main
    with:
      artifact-name: kodata-www-metarex-media
      docker_ns: ${{ vars.DOCKER_NS }}
    secrets:
      docker_pat: ${{ secrets.DOCKER_PAT }}
      get_clog: ${{ secrets.GET_CLOG }}
      # provide a slack_webhook to get a slack message otherwise silence
      webhook_slack: ${{ secrets.HOOK_SLACK_LOGS }}
      
  #dump properties of the build output / needs context
  dump-context:
    needs: [build]
    uses: mrmxf/clog/.github/workflows/dump-context.yaml@main
